### ISSUE TITLE
Table: Columns not updating correctly when passing new column layout.

### ISSUE THREAD

**Issue by jwahdatehagh** [rafaelpimpa/buefy#108]
### Overview of the problem

**Buefy** version: [0.4.0]
**Vuejs** version: [2.3.1]

### Description
I have the table-columns in a loop like so:
```html
<b-table-column
  v-for="(field, index) in ModelClass.overviewFields"
  :key="index"
  :field="field.key"
  :label="field.label"
>
  {{ props.row.attributes[field.key] }}
</b-table-column>
```
That way, i can dynamically change the layout of the table in a data-driven way. 

### Steps to reproduce

1. See above html
2. Update `ModelClass.overviewFields` a couple of times -> the columns get messed up.

The problem lies within the way the `<td>`-components edit the tables `column`-property in [TableColumn.vue](https://github.com/rafaelpimpa/buefy/blob/dev/src/components/table/TableColumn.vue#L35-L38):
```js
const repeated = this.$parent.columns.some((column) => {
  return column.label === this.label
})
!repeated && this.$parent.columns.push(this.$props)
```
The columns should be reset before refilled.

### Expected behaviour
The table component should correctly recalculate the column labels.

**Comment by rafaelpimpa** [comment]
This is fixed in next release (v0.4.1), columns will be reactive.

**Comment by timaronan** [comment]
I still have this same issue with (v0.6.2). are column headers reactive yet?

**Comment by psweeting1** [comment]
This is still a problem, I'm using (v0.6.2) as well. Column headers are not reactive.

**Comment by jwahdatehagh** [comment]
I can also confirm - not reactive yet... I have a workaround (completely reset the table):
```js
resetTable () {
  // Reset columns (prevent buefy bug where columns add up)
  this.$refs.table.columns = []

  // ...
}
```

**Comment by psweeting1** [comment]
Jwahdatehagh, where did you place this fix?

**Comment by jwahdatehagh** [comment]
@psweeting1 in the component that contains the `<b-table`. I call it just before the structure of the table (columns) changes.

```
<template>
  <b-table
    ref="table"
    // ...
  >
    // ...
  </b-table>
</template>

<script>
export default {

  // ...

  methods: {
    resetTable () {
      // Reset columns (prevent buefy bug where columns add up)
      this.$refs.table.columns = []

      // ...
    },

    // ...
  }
}
</script>
```

**Comment by psweeting1** [comment]
Many thanks jwahdatehagh!

**Comment by rafaelpimpa** [comment]
Could you create another issue if it's still a thing?

**Comment by tanhs** [comment]
@jwahdatehagh this.$refs.table.columns = [] getting error as below.
@rafaelpimpa , i tried columns=[], it doesn't help.
`Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "columns"`

**Comment by talismax** [comment]
I don't see where @tanhs question was ever answered. I have the same issue with dynamic columns. I can't fix it because the problem is in the table component. 

![image](https://user-images.githubusercontent.com/2261681/46105022-8c6edc00-c19a-11e8-82e9-e9cefb8672cd.png)

**Comment by jwahdatehagh** [comment]
Yeah my answer did work half a year ago. Now i just rerender the entire table when columns change by leveraging `v-if` on the table (in my usecase i'm setting 'loading' to true just before doing an ajax call, so Vue will definitely rerender the table.

```html
<b-table
  v-if="!loading"
  :data="data"
>
  // ...
</b-table>
```

You could achieve the same thing by toggling the table like this:
```js
changeColumns () {
  this.showTable = false
  this.$nextTick(() => this.showTable = true)
}
```
(given you have a `<b-table v-if="showTable">`)
