### ISSUE TITLE
AutoComplete: using a '*' as a search term (v-model)

### ISSUE THREAD

**Issue by dandob74** [rafaelpimpa/buefy#336]
Hi,
When using a '*' for the search query (v-model) the getValue method tries to create a RegExp for the given String to highlight the results.

Unfortunately, this leads to an exception:
Invalid regular expression: /(*)/: Nothing to repeat
and the user won`t get any results.

I tried to achieve to return all entries when querying for '*'.

Any clue?

Thanks and best,
Daniel

**Comment by jtommy** [comment]
There is an issue in the current version but it's fixed by https://github.com/rafaelpimpa/buefy/issues/315

**Comment by dandob74** [comment]
Hi,
thanks for the quick response. Unfortunately I think this is a different issue in #315.

I updated the jsfiddle to outline my issue: http://jsfiddle.net/sepck7mq/2/

Just insert a * (asterisk)  in the search box and you will see an exception in the console:
 ... SyntaxError: Invalid regular expression: /(*)/: Nothing ...

Cheers,
Daniel

**Comment by jtommy** [comment]
Your example doesn't work because it's not correct, let's try http://jsfiddle.net/jzxee0fs/.
Anyway the issue is the same and it's fixed (ready in next release)

**Comment by dandob74** [comment]
Hi,
Your jsfiddle behave the same like mine.  Both jsfiddles throw an exception: SyntaxError: Invalid regular expression: /(*)/: Nothing ...

If it's fixed with the next release, perfect!!! 
Thanks, Daniel

**Comment by jtommy** [comment]
Yes, the issue is still alive :smile: (please wait next release) but your example it wasn't correct because you didn't set computed property to `data` prop.

**Comment by dandob74** [comment]
Yep, I got it.  I just wanted to be sure that you see the exception.  I'll wait for the next realse.  commit  ba58132 looks promising!
