### ISSUE TITLE
Clearing b-autocomplete selection?

### ISSUE THREAD

**Issue by philipithomas** [rafaelpimpa/buefy#380]
### Overview of the problem

Clearing the b-autocomplete after a selection results in an error.

**Buefy** version:  0.5.4
**Vuejs** version: 2.4.4
**OS/Browser**: Chrome latest

### Description

It is unclear how to clear a selection in the b-autocomplete component. 

### Steps to reproduce

`<b-autocomplete v-model="query" />`

1. Make selection with autocomplete
2. `this.query = null` to clear query
3. Get error

### Expected behavior

Clears without error

### Actual behavior

<img width="834" alt="screen shot 2017-10-23 at 2 22 15 pm" src="https://user-images.githubusercontent.com/1312414/31913953-c34d929a-b7fd-11e7-9aeb-83dfa0376196.png">

**Comment by jtommy** [comment]
@philipithomas Thanks, we'll fix it! 
At the moment you can clear input by `this.query = ''`

**Comment by philipithomas** [comment]
Thanks. I've also noticed a race condition where, if you clear the query after @selected event,  the component overwrites it shortly afterward. I fixed for now but waiting 50ms after @selected before clearing, but it's kind of clunky

**Comment by jbender** [comment]
This is still an issue (the race condition, setting to `null` no longer throws)

**Comment by DesiredApp** [comment]
`setTimeout(() => this.query = '', 10); ` did the trick
